export const GET_FILM_ADMIN = 'GET_FILM_ADMIN'

export const ADD_FILM_ADMIN = 'ADD_FILM_ADMIN'

export const DELETE_FILM_ADMIN = 'DELETE_FILM_ADMIN'

export const ITEM_EDITING = 'ITEM_EDITING'


export const GET_THEATRES = 'GET_THEATRES';

export const GET_THEATRE = 'GET_THEATRE'

export const ADD_A_THEATRE = 'ADD_A_THEATRE';

export const DELETE_THEATRE = 'DELETE_THEATRE'

export const UPDATE_THEATRE = 'UPDATE_THEATRE'